export const APP_AUTH_INIT = "APP_AUTH_INIT";
export const APP_TOAST_ADD = "APP_TOAST_ADD";
export const APP_TOAST_REMOVE = "APP_TOAST_REMOVE";
export const APP_TOAST_CLEAR = "APP_TOAST_CLEAR";

export const LOGIN_USER_AUTH_INIT = "LOGIN_USER_AUTH_INIT";
export const LOGOUT_USER_AUTH_UPDATE = "LOGOUT_USER_AUTH_UPDATE";

export const USER_UPDATE_DETAILS = "USER_UPDATE_DETAILS";

export const HOME_TOGGLE_SETTINGS = "HOME_TOGGLE_SETTINGS";




